title: "Enigma"
author: mehmoodosman
email: osman.mehmood2@gmail.com
description: "Your desires and imagination should be in sync. Bravery is what we do despite that fear."

# social links
twitter_username: mehmoodosman
github_username: mehmoodosman

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
